"""Complete dependency lock with hashes for requirements.txt / requirements-dev.txt (ADR 0082).

fml names every package that ends up on a user's machine. The requirement
files therefore list the FULL dependency closure, every entry pinned with
``==`` and with the SHA-256 hashes of all its files on PyPI. The start
scripts install in hash-checking mode (``--require-hashes``), so pip refuses
any package that is not listed here, including build-time downloads
(``--only-binary=:all:``).

Source of truth are the entries marked ``# direct: <where>``; everything
else is regenerated:

    python tools/lock_deps.py            # rewrite both files
    python tools/lock_deps.py --check    # exit 1 when a file is out of date

How versions are chosen: direct pins as written; transitive packages at the
version installed in the current venv (pip already resolved them), and for
packages that are only needed on other platforms (e.g. colorama on Windows)
the newest release on PyPI that satisfies every requirement on it. Markers
are evaluated for Python 3.12-3.14 on Linux, macOS and Windows.

Raising a pin: edit the direct line, ``pip install -r requirements-dev.txt``,
run this script, run ``pytest -q``, update DEPENDENCIES.md.

Uses only the standard library plus ``pip._vendor.packaging`` (the
requirement/marker/version parser that ships inside pip itself).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from dataclasses import dataclass, field
from importlib import metadata
from pathlib import Path
from typing import Callable

from pip._vendor.packaging.markers import Marker
from pip._vendor.packaging.requirements import Requirement
from pip._vendor.packaging.specifiers import SpecifierSet
from pip._vendor.packaging.version import Version

ROOT = Path(__file__).resolve().parents[1]
RUNTIME = "requirements.txt"
DEV = "requirements-dev.txt"

PYTHONS = ("3.12", "3.13", "3.14")
PLATFORMS = (
    {"sys_platform": "linux", "platform_system": "Linux", "os_name": "posix", "platform_machine": "x86_64"},
    {"sys_platform": "darwin", "platform_system": "Darwin", "os_name": "posix", "platform_machine": "arm64"},
    {"sys_platform": "win32", "platform_system": "Windows", "os_name": "nt", "platform_machine": "AMD64"},
)
ENVS = [
    {**plat, "python_version": py, "python_full_version": py + ".0",
     "implementation_name": "cpython", "platform_python_implementation": "CPython", "extra": ""}
    for py in PYTHONS for plat in PLATFORMS
]

_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;\\]+)")
HEADER = {
    RUNTIME: """\
# Runtime dependencies: the COMPLETE set of packages fml installs, each pinned
# and hashed. Generated by tools/lock_deps.py from the entries marked
# "# direct" (see DEPENDENCIES.md for what each one does and why).
# start.sh / start.bat install this file with --require-hashes and
# --only-binary=:all:, so pip refuses any package or file that is not listed.
""",
    DEV: """\
# Development dependencies (tests): runtime lock plus pytest and its closure,
# each pinned and hashed. Generated by tools/lock_deps.py.
# Install: python -m pip install --require-hashes --only-binary=:all: -r requirements-dev.txt
""",
}


def norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


@dataclass
class Entry:
    name: str
    version: str
    direct: str | None = None          # "where" text for direct entries
    marker: str = ""                   # environment marker, "" = everywhere
    via: set[str] = field(default_factory=set)
    hashes: list[str] = field(default_factory=list)


# -- reading ------------------------------------------------------------------

def read_direct(path: Path) -> dict[str, Entry]:
    """Direct entries of a requirement file: ``name==version`` followed by a
    ``# direct: where`` comment (inline or on one of the next comment lines)."""
    out: dict[str, Entry] = {}
    current: Entry | None = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        m = _PIN.match(line)
        if m:
            current = Entry(m.group(1), m.group(2))
            inline = line.split("#", 1)[1] if "#" in line else ""
            if inline.strip().startswith("direct:"):
                current.direct = inline.strip()[len("direct:"):].strip()
                out[norm(current.name)] = current
            continue
        if current and line.startswith("# direct:"):
            current.direct = line[len("# direct:"):].strip()
            out[norm(current.name)] = current
        elif line and not line.startswith(("#", "--")):
            current = None
    return out


# -- PyPI ---------------------------------------------------------------------

def _get_json(url: str) -> dict:
    with urllib.request.urlopen(url, timeout=30) as resp:   # noqa: S310 (fixed https host)
        return json.load(resp)


@dataclass
class Index:
    """PyPI lookups; ``fetch`` is injectable for tests."""
    fetch: Callable[[str], dict] = _get_json

    def release(self, name: str, version: str) -> dict:
        return self.fetch(f"https://pypi.org/pypi/{name}/{version}/json")

    def project(self, name: str) -> dict:
        return self.fetch(f"https://pypi.org/pypi/{name}/json")

    def hashes(self, name: str, version: str) -> list[str]:
        files = self.release(name, version)["urls"]
        if not any(f["packagetype"] == "bdist_wheel" for f in files):
            raise SystemExit(f"{name}=={version} has no wheel on PyPI; --only-binary would fail")
        return sorted(f["digests"]["sha256"] for f in files)

    def requires(self, name: str, version: str) -> list[str]:
        return self.release(name, version)["info"].get("requires_dist") or []

    def newest(self, name: str, spec: SpecifierSet) -> str:
        releases = self.project(name)["releases"]
        ok = [Version(v) for v, files in releases.items()
              if files and not all(f.get("yanked") for f in files)
              and not Version(v).is_prerelease and Version(v) in spec]
        if not ok:
            raise SystemExit(f"no release of {name} satisfies {spec}")
        return str(max(ok))


def _installed(name: str) -> str | None:
    try:
        return metadata.version(name)
    except metadata.PackageNotFoundError:
        return None


def _installed_requires(name: str, version: str) -> list[str] | None:
    if _installed(name) == version:
        return metadata.requires(name) or []
    return None


# -- closure ------------------------------------------------------------------

def resolve(direct: dict[str, Entry], index: Index, *, exclude: set[str] = frozenset(),
            installed: Callable[[str], str | None] = _installed,
            installed_requires: Callable[[str, str], list[str] | None] = _installed_requires,
            ) -> dict[str, Entry]:
    """Full closure of ``direct`` over all ENVS. Returns entries by normalized
    name (``exclude``: names already locked elsewhere, e.g. runtime for dev)."""
    entries: dict[str, Entry] = {k: Entry(e.name, e.version, e.direct) for k, e in direct.items()}
    envs_of: dict[str, set[int]] = {k: set(range(len(ENVS))) for k in entries}
    markers_of: dict[str, set[str]] = {k: set() for k in entries}
    specs: dict[str, SpecifierSet] = {}
    queue = list(entries)
    while queue:
        key = queue.pop(0)
        entry = entries[key]
        reqs = installed_requires(entry.name, entry.version)
        if reqs is None:
            reqs = index.requires(entry.name, entry.version)
        for raw in reqs:
            req = Requirement(raw)
            child = norm(req.name)
            hit = {i for i in envs_of[key]
                   if req.marker is None or req.marker.evaluate(ENVS[i])}
            if not hit:
                continue
            if child in exclude:
                continue
            specs[child] = specs.get(child, SpecifierSet()) & req.specifier
            if child not in entries:
                version = installed(req.name) or index.newest(req.name, specs[child])
                entries[child] = Entry(req.name, version)
                envs_of[child], markers_of[child] = set(), set()
            entries[child].via.add(entry.name)
            new = hit - envs_of[child]
            if req.marker is not None and len(hit) < len(ENVS):
                if len(envs_of[key]) < len(ENVS) and markers_of[key]:
                    raise SystemExit(f"nested conditional dependency {entry.name} -> {req.name}: "
                                     "extend tools/lock_deps.py before locking this")
                markers_of[child].add(str(req.marker))
            if new:
                envs_of[child] |= new
                queue.append(child)
    for key, entry in entries.items():
        if Version(entry.version) not in specs.get(key, SpecifierSet()):
            raise SystemExit(f"{entry.name}=={entry.version} violates {specs[key]}")
        if len(envs_of[key]) < len(ENVS):
            entry.marker = " or ".join(f"({m})" for m in sorted(markers_of[key])) \
                if len(markers_of[key]) > 1 else next(iter(markers_of[key]))
        entry.hashes = index.hashes(entry.name, entry.version)
    return entries


# -- writing ------------------------------------------------------------------

def render(filename: str, entries: dict[str, Entry], *, include: str | None = None) -> str:
    lines = [HEADER[filename]]
    if include:
        lines.append(f"-r {include}\n")
    for key in sorted(entries):
        e = entries[key]
        head = f"{e.name}=={e.version}" + (f" ; {e.marker}" if e.marker else "")
        lines.append(head + " \\")
        for i, h in enumerate(e.hashes):
            lines.append(f"    --hash=sha256:{h}" + (" \\" if i < len(e.hashes) - 1 else ""))
        if e.direct:
            lines.append(f"    # direct: {e.direct}")
        if e.via:
            lines.append(f"    # via {', '.join(sorted(e.via, key=str.lower))}")
    return "\n".join(lines) + "\n"


def build(root: Path, index: Index) -> dict[str, str]:
    runtime_direct = read_direct(root / RUNTIME)
    runtime = resolve(runtime_direct, index)
    dev_direct = read_direct(root / DEV)
    dev = resolve(dev_direct, index, exclude=set(runtime))
    return {RUNTIME: render(RUNTIME, runtime), DEV: render(DEV, dev, include=RUNTIME)}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Regenerate the complete, hashed dependency lock.")
    ap.add_argument("--check", action="store_true", help="only report files that are out of date")
    args = ap.parse_args(argv)
    stale = 0
    for name, text in build(ROOT, Index()).items():
        path = ROOT / name
        if path.read_text(encoding="utf-8") == text:
            print(f"{name}: up to date")
            continue
        stale += 1
        if args.check:
            print(f"{name}: OUT OF DATE - run python tools/lock_deps.py")
        else:
            path.write_text(text, encoding="utf-8")
            print(f"{name}: rewritten")
    return 1 if (args.check and stale) else 0


if __name__ == "__main__":
    sys.exit(main())
